### ISSUE TITLE
Release issue

### ISSUE THREAD

**Issue by UwUDev** [jacobr1227/double_seals#1]
Hi, i wanted to add your mods to the marketplace but the tar is not valid, you should take a look at sbordeyne's mods [releases](https://github.com/sbordeyne/balamod-mods/releases/latest) and [workflows](https://github.com/sbordeyne/balamod-mods/tree/master/.github/workflows)

**Comment by jacobr1227** [comment]
@UwUDev Did y'all ever work out a viable solution for modpack-type repos? Or does it make more sense for me to split/unify this one as I see fit. This one was an issue for the marketplace before because I contained 3 separate but interoperable mods in one place.

**Comment by jacobr1227** [comment]
@UwUDev My mistake, I didn't look too thoroughly at the workflows page yesterday. I have corrected the issue, and there are now 3 files in the release with the proper formatting. Please let me know if there's anything else that needs doing to get this working.

**Comment by UwUDev** [comment]
If it's all good then make a PR on this file https://github.com/balamod/mods/blob/main/index.json

Also make sure that your version tag matches the mod version and check if the version is formatted like this `[0-9]+\.[0-9]+\.[0-9]+`

**Comment by jacobr1227** [comment]
Fixed and sent.
